version: '3.5'
services:
#  gateway:
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    networks:
#      - network
#    volumes:
#      - 'gateway_data:/app/static'
#    depends_on:
#      - postgres

  postgres:
    image: mdillon/postgis:11-alpine
    ports:
      - '5432:5432'
    networks:
      - network
    #    volumes:
    #      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge

volumes:
  gateway_data:
  postgres_data:
